
--CREATE USER IF NOT EXISTS VEM_SER IDENTIFIED BY oracle;
--GRANT CONNECT TO VEM_SER;
--GRANT CONNECT, RESOURCE, DBA TO VEM_SER;
--GRANT CREATE SESSION TO VEM_SER;
--GRANT DBA TO VEM_SER;
--GRANT CREATE VIEW, CREATE PROCEDURE, CREATE SEQUENCE to VEM_SER;
--GRANT UNLIMITED TABLESPACE TO VEM_SER;
--GRANT CREATE MATERIALIZED VIEW TO VEM_SER;
--GRANT CREATE TABLE TO VEM_SER;
--GRANT GLOBAL QUERY REWRITE TO VEM_SER;
--GRANT SELECT ANY TABLE TO VEM_SER;

CREATE TABLE VEM_SER.ESTUDANTE (
	id_estudante NUMBER NOT NULL,
	nome VARCHAR2(200) NOT NULL,
	data_nascimento DATE NOT NULL,
	nr_matricula NUMBER(10) NOT NULL,
	ativo CHAR(1),
	PRIMARY KEY(id_estudante)
);

CREATE SEQUENCE seq_estudante
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

CREATE SEQUENCE seq_matricula_estudante
START WITH 100
INCREMENT BY 1
NOCACHE NOCYCLE;

INSERT INTO VEM_SER.ESTUDANTE (ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES (SEQ_ESTUDANTE.nextval, 'Lucas K. P', TO_DATE('19-06-2002', 'dd-mm-yyyy'), VEM_SER.seq_matricula_estudante.nextval, 'S');
INSERT INTO VEM_SER.ESTUDANTE (ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES (VEM_SER.seq_estudante.nextval, 'Nicolas', TO_DATE('02-02-2003', 'dd-mm-yyyy'), VEM_SER.seq_matricula_estudante.nextval, 'S');
INSERT INTO VEM_SER.ESTUDANTE (ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES (VEM_SER.seq_estudante.nextval, 'Nicole', TO_DATE('21-09-2001', 'dd-mm-yyyy'), VEM_SER.seq_matricula_estudante.nextval, 'S');
INSERT INTO VEM_SER.ESTUDANTE (ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES (VEM_SER.seq_estudante.nextval, 'Ana Vitória', TO_DATE('11-11-2002', 'dd-mm-yyyy'), VEM_SER.seq_matricula_estudante.nextval, 'S');
INSERT INTO VEM_SER.ESTUDANTE (ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES (VEM_SER.seq_estudante.nextval, 'Thiago K', TO_DATE('16-06-2002', 'dd-mm-yyyy'), VEM_SER.seq_matricula_estudante.nextval, 'N');
INSERT INTO VEM_SER.ESTUDANTE (ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES (VEM_SER.seq_estudante.nextval, 'Gilliard', TO_DATE('01-02-1983', 'dd-mm-yyyy'), VEM_SER.seq_matricula_estudante.nextval, 'N');
INSERT INTO VEM_SER.ESTUDANTE (ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES (VEM_SER.seq_estudante.nextval, 'Jean Reverson', TO_DATE('20-09-1978', 'dd-mm-yyyy'), VEM_SER.seq_matricula_estudante.nextval, 'S');
INSERT INTO VEM_SER.ESTUDANTE (ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES (VEM_SER.seq_estudante.nextval, 'Joãozin', TO_DATE('01-01-2001', 'dd-mm-yyyy'), VEM_SER.seq_matricula_estudante.nextval, 'S');
INSERT INTO VEM_SER.ESTUDANTE (ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES (VEM_SER.seq_estudante.nextval, 'Jacinto', TO_DATE('06-06-2006', 'dd-mm-yyyy'), VEM_SER.seq_matricula_estudante.nextval, 'S');
INSERT INTO VEM_SER.ESTUDANTE (ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES (VEM_SER.seq_estudante.nextval, 'Paulão da Roça', TO_DATE('10-04-1972', 'dd-mm-yyyy'), VEM_SER.seq_matricula_estudante.nextval, 'N');

SELECT * FROM VEM_SER.ESTUDANTE;
	


